#!/bin/bash
source "$(dirname ${BASH_SOURCE})/common.sh"

info "sudo openshift start --public-master=localhost $@"
sudo /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/openshift start --public-master=localhost "$@"
