#!/bin/bash
source "$(dirname ${BASH_SOURCE})/common.sh"

info "Adding view role to 'demo' user in the default namespace ..."
oadm policy add-role-to-user view demo -n default

info "Creating Docker registry ..."
oadm registry -n default

# FIXME create a router

info "Done."
