#!/bin/bash
source "$(dirname ${BASH_SOURCE})/common.sh"

NAME="${NAME:-demo}"
DISPLAY_NAME="${DISPLAY_NAME:-OpenShift Demo Project}"
DESCRIPTION="${DESCRIPTION:-This is a demo project}"

info "Creating project '${NAME}' ..."
oc new-project "${NAME}" --display-name="${DISPLAY_NAME}" --description="${DESCRIPTION}"
oadm policy add-role-to-user admin demo -n "${NAME}"

info "Done."
